/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/monitoring/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/backtests`. */
        get: operations["list_backtests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/backtests/{run_id}`. */
        get: operations["get_backtest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/backtests/{run_id}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/backtests/{run_id}/candles`. */
        get: operations["get_backtest_candles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/backtests/{run_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/backtests/{run_id}/decisions`. */
        get: operations["get_backtest_decisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/backtests/{run_id}/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/backtests/{run_id}/fills`. */
        get: operations["get_backtest_fills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/backtests/{run_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/backtests/{run_id}/metrics`. */
        get: operations["get_backtest_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/backtests/{run_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/backtests/{run_id}/orders`. */
        get: operations["get_backtest_orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/candles`. */
        get: operations["get_candles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/strategies`. */
        get: operations["list_strategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/strategies/{id}/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/strategies/{id}/fills`. */
        get: operations["get_strategy_fills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/strategies/{id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/strategies/{id}/orders`. */
        get: operations["get_orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitoring/timeframes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handler for `GET /api/v1/monitoring/timeframes`. */
        get: operations["get_timeframes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response for the run candles endpoint: the OHLC series plus a source hint. */
        BacktestCandlesDto: {
            /** @description Aggregated OHLC buckets (empty when `source = none`). */
            candles: components["schemas"]["CandleDto"][];
            /**
             * @description `candles_5s` when the run window is covered, `none` for the degraded
             *     timeline-only view (no OHLC background available).
             * @example candles_5s
             */
            source: string;
        };
        /** @description JSON error body for the backtest endpoints. */
        BacktestErrorBody: {
            /** @description Whitelisted values for `invalid_status`. */
            allowed?: string[] | null;
            /** @description Machine-readable discriminator (e.g. `invalid_range`). */
            error: string;
            /** @description Applicable row cap for `too_many_rows`. */
            max?: number | null;
            /** @description Human-readable explanation. */
            message?: string | null;
            /** @description Echoes the requested row count for `too_many_rows`. */
            requested?: number | null;
        };
        /**
         * @description Recomputed performance metrics for a run (from `fills_backtest`, §5 recipe).
         *
         *     PnL/fees are cash-flow figures derived from the per-side aggregates; see
         *     [`domain::backtest::BacktestMetrics`] for the exact definition and the
         *     flat-position caveat. Money fields are quote-currency `f64` at this boundary.
         */
        BacktestMetricsDto: {
            /**
             * Format: int64
             * @description Number of buy fills.
             */
            buy_fills: number;
            /**
             * Format: double
             * @description Quote spent on buys.
             */
            buy_notional: number;
            /**
             * Format: double
             * @description Total bought base-asset quantity.
             */
            buy_quantity: number;
            /**
             * Format: double
             * @description Gross cash-flow PnL (`sell_notional - buy_notional`, pre-fees).
             */
            gross_pnl: number;
            /**
             * Format: double
             * @description Net cash-flow PnL (`gross_pnl - total_fees`).
             */
            net_pnl: number;
            /**
             * Format: int64
             * @description Number of sell fills.
             */
            sell_fills: number;
            /**
             * Format: double
             * @description Quote received from sells.
             */
            sell_notional: number;
            /**
             * Format: double
             * @description Total sold base-asset quantity.
             */
            sell_quantity: number;
            /**
             * Format: double
             * @description Total fees over all fills.
             */
            total_fees: number;
        };
        /** @description One backtest order (chart marker). */
        BacktestOrderDto: {
            /**
             * Format: uuid
             * @description Foreign key to the decision.
             */
            decision_id: string;
            /**
             * Format: date-time
             * @description Market-clock timestamp (RFC3339).
             */
            market_ts: string;
            /**
             * Format: uuid
             * @description Primary key.
             */
            order_id: string;
            /**
             * Format: double
             * @description Best-effort price `COALESCE(limit_price, expected_price)`; `null` when unknown.
             */
            price?: number | null;
            /**
             * Format: double
             * @description Base-asset quantity.
             */
            quantity: number;
            /**
             * @description `buy` or `sell`.
             * @example buy
             */
            side: string;
            /**
             * @description Raw status string (free text — `orders_backtest.status` has no `CHECK`).
             * @example filled
             */
            status: string;
        };
        /** @description A run with its opaque configuration snapshot (detail view). */
        BacktestRunDetailDto: {
            /** @description Opaque, display-only configuration snapshot (`jsonb` object). */
            config_snapshot: Record<string, never>;
            /** @description The run summary. */
            run: components["schemas"]["BacktestRunSummaryDto"];
        };
        /** @description Summary of a backtest run (list item). */
        BacktestRunSummaryDto: {
            /**
             * Format: date-time
             * @description Exclusive end of the replayed market window (RFC3339, market clock).
             */
            data_range_end: string;
            /**
             * Format: date-time
             * @description Inclusive start of the replayed market window (RFC3339, market clock).
             */
            data_range_start: string;
            /**
             * Format: date-time
             * @description Wall-clock time the run ended; absent while `status = running`.
             */
            ended_at?: string | null;
            /** @description Failure description when `status = failed`; absent otherwise. */
            error?: string | null;
            /**
             * @description Exchange identifier.
             * @example binance
             */
            exchange: string;
            /**
             * Format: int32
             * @description Simulated Binance taker fee in basis points.
             */
            fee_binance_bps: number;
            /**
             * Format: int32
             * @description Simulated Kraken taker fee in basis points.
             */
            fee_kraken_bps: number;
            /**
             * Format: uuid
             * @description Primary key.
             */
            id: string;
            /**
             * Format: int32
             * @description Simulated execution latency in milliseconds.
             */
            latency_ms: number;
            /**
             * Format: int32
             * @description Simulated slippage in basis points.
             */
            slippage_bps: number;
            /**
             * Format: date-time
             * @description Wall-clock time the run started (RFC3339).
             */
            started_at: string;
            /**
             * @description Lifecycle state (`running`, `completed`, `failed`, `aborted`).
             * @example completed
             */
            status: string;
            /**
             * Format: uuid
             * @description Optional synthetic strategy id (nullable, no FK).
             */
            strategy_id?: string | null;
            /**
             * @description Strategy family label.
             * @example ma_cross
             */
            strategy_kind: string;
            /**
             * @description Symbol identifier.
             * @example BTCUSDT
             */
            symbol: string;
        };
        /**
         * @description HTTP DTO returned in the JSON array.
         *
         *     We deliberately down-cast `Decimal` → `f64` at the serialisation boundary:
         *     Lightweight Charts requires JS numbers, and the relative error introduced
         *     (worst case ≈ 2.2e-16 for typical OHLC magnitudes) is invisible at chart
         *     pixel resolution. The full-precision `Decimal` stays in the domain and the
         *     persistence layer — only this struct loses precision, and it is the only
         *     place that does.
         */
        CandleDto: {
            /**
             * Format: double
             * @description Close price.
             */
            c: number;
            /**
             * Format: double
             * @description High price.
             */
            h: number;
            /**
             * Format: double
             * @description Low price.
             */
            l: number;
            /**
             * Format: double
             * @description Open price.
             */
            o: number;
            /**
             * Format: date-time
             * @description Bucket start, RFC3339 (e.g. `2026-05-27T14:00:00Z`).
             */
            ts: string;
            /**
             * Format: double
             * @description Total traded volume in the bucket.
             */
            v: number;
        };
        /** @description JSON error body returned on 4xx / 5xx by the candles endpoint. */
        CandleErrorBody: {
            /** @description Whitelisted `timeframe` values, surfaced for `invalid_timeframe`. */
            allowed?: string[] | null;
            /** @description Machine-readable error discriminator (e.g. `invalid_timeframe`). */
            error: string;
            /** @description Maximum bucket count accepted by the endpoint for `too_many_points`. */
            max?: number | null;
            /** @description Human-readable explanation (optional). */
            message?: string | null;
            /** @description Echoes the caller-supplied bucket count for `too_many_points`. */
            requested?: number | null;
        };
        /** @description One strategy decision (marker + optional context snapshot). */
        DecisionDto: {
            /**
             * Format: uuid
             * @description Primary key.
             */
            decision_id: string;
            /**
             * Format: date-time
             * @description Market-clock timestamp (RFC3339).
             */
            market_ts: string;
            /**
             * Format: int32
             * @description Number of orders emitted by this decision.
             */
            orders_count: number;
            /** @description Free-text rationale recorded by the strategy engine. */
            reason: string;
            /** @description Opaque market-context snapshot (`jsonb`); absent when no context recorded. */
            snapshot?: Record<string, never> | null;
        };
        /** @description One trade fill. */
        FillDto: {
            /**
             * Format: double
             * @description Fee charged for this fill.
             */
            fee: number;
            /**
             * @description Asset the fee was charged in.
             * @example USDT
             */
            fee_asset: string;
            /**
             * Format: uuid
             * @description Primary key.
             */
            fill_id: string;
            /**
             * Format: date-time
             * @description Market-clock timestamp (RFC3339).
             */
            market_ts: string;
            /**
             * Format: uuid
             * @description Order that produced this fill.
             */
            order_id: string;
            /**
             * Format: double
             * @description Execution price.
             */
            price: number;
            /**
             * Format: double
             * @description Executed base-asset quantity.
             */
            quantity: number;
            /**
             * @description `buy` or `sell`.
             * @example sell
             */
            side: string;
        };
        /** @description A live fill (execution marker). */
        LiveFillDto: {
            /**
             * Format: date-time
             * @description Wall-clock execution time (RFC3339).
             */
            executed_at: string;
            /**
             * Format: double
             * @description Fee charged for this fill.
             */
            fee: number;
            /**
             * @description Asset the fee was charged in.
             * @example USDT
             */
            fee_asset: string;
            /**
             * Format: uuid
             * @description Primary key.
             */
            fill_id: string;
            /** @description Whether this fill is paper trading. */
            is_paper: boolean;
            /**
             * Format: uuid
             * @description Order that produced this fill.
             */
            order_id: string;
            /**
             * Format: double
             * @description Execution price.
             */
            price: number;
            /**
             * Format: double
             * @description Executed base-asset quantity.
             */
            quantity: number;
            /**
             * @description `buy` or `sell`.
             * @example buy
             */
            side: string;
        };
        /**
         * @description HTTP DTO returned in the JSON array for the orders endpoint.
         *
         *     `Decimal -> f64` happens at this boundary only (see candles handler
         *     rationale). For OHLC magnitudes the worst-case relative error
         *     (~2.2e-16) is invisible at chart pixel resolution; the full-precision
         *     `Decimal` stays in the domain and persistence layers.
         */
        OrderDto: {
            /**
             * Format: date-time
             * @description Wall-clock time the row was inserted (RFC3339).
             */
            created_at: string;
            /**
             * Format: uuid
             * @description Foreign key to `strategy_decisions(id)`.
             */
            decision_id: string;
            /**
             * Format: uuid
             * @description Primary key.
             */
            order_id: string;
            /**
             * Format: double
             * @description Best-effort price: `COALESCE(limit_price, expected_price)`.
             *
             *     - For `limit` / `amend` orders, this is the explicit limit price.
             *     - For `market` orders, this is the `expected_price` recorded by the
             *       strategy engine just before submission, when available.
             *     - `null` when neither is known (e.g. `market` without expected price).
             */
            price?: number | null;
            /**
             * Format: double
             * @description Base-asset quantity.
             */
            quantity: number;
            /**
             * @description `buy` or `sell` (DB enum).
             * @example buy
             */
            side: string;
            /**
             * @description Lifecycle status (`submitted`, `filled`, `canceled`, …).
             * @example filled
             */
            status: string;
        };
        /** @description JSON error body returned on 4xx / 5xx by the orders endpoint. */
        OrderErrorBody: {
            /**
             * @description Whitelisted `side` values, surfaced for `invalid_side` (currently
             *     unused — the handler does not parse `side` from input, but kept for
             *     schema symmetry with the candles error body).
             */
            allowed?: string[] | null;
            /** @description Machine-readable error discriminator (e.g. `invalid_range`). */
            error: string;
            /** @description Maximum row count accepted by the endpoint for `too_many_rows`. */
            max?: number | null;
            /** @description Human-readable explanation (optional). */
            message?: string | null;
            /** @description Echoes the caller-supplied row count for `too_many_rows`. */
            requested?: number | null;
        };
        /** @description A strategy row (selector item). */
        StrategyDto: {
            /** @description Whether the strategy is enabled for live trading. */
            enabled_live: boolean;
            /** @description Whether the strategy is enabled for paper trading. */
            enabled_paper: boolean;
            /**
             * Format: uuid
             * @description Primary key.
             */
            id: string;
            /**
             * @description Strategy kind/family.
             * @example directional
             */
            kind: string;
            /** @description Unique human-readable name. */
            name: string;
        };
        /** @description JSON error body for the strategy endpoints. */
        StrategyErrorBody: {
            /** @description Machine-readable error discriminator. */
            error: string;
            /** @description Maximum row count for `too_many_rows`. */
            max?: number | null;
            /** @description Human-readable explanation. */
            message?: string | null;
            /** @description Echoes the requested row count for `too_many_rows`. */
            requested?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_backtests: {
        parameters: {
            query?: {
                /** @description Optional `status` filter (`running`/`completed`/`failed`/`aborted`). */
                status?: string | null;
                /** @description Optional `strategy_kind` filter. */
                strategy_kind?: string | null;
                /** @description Optional `exchange` filter. */
                exchange?: string | null;
                /** @description Optional `symbol` filter. */
                symbol?: string | null;
                /** @description Row cap (defaults to and rejected above `MAX_BACKTEST_RUNS`). */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backtest runs ordered by descending `started_at`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunSummaryDto"][];
                };
            };
            /** @description Invalid `status` filter or `limit` out of bounds. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
        };
    };
    get_backtest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Backtest run identifier */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run and its configuration snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunDetailDto"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No run with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
        };
    };
    get_backtest_candles: {
        parameters: {
            query: {
                /** @description Aggregation width (must be one of [`Timeframe::ALLOWED`]). */
                timeframe: string;
            };
            header?: never;
            path: {
                /** @description Backtest run identifier */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated candles_5s over the run's market window, with a `source` hint. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestCandlesDto"];
                };
            };
            /** @description Invalid timeframe or window exceeding the bucket cap. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No run with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
        };
    };
    get_backtest_decisions: {
        parameters: {
            query: {
                /** @description Inclusive lower bound on `market_ts` (RFC3339). */
                from: string;
                /** @description Exclusive upper bound on `market_ts` (RFC3339). Defaults to `Clock::now()`. */
                to?: string | null;
                /** @description Row cap (defaults to and rejected above `MAX_ORDER_ROWS`). */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Backtest run identifier */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run decisions on the window, ordered by ascending `market_ts`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDto"][];
                };
            };
            /** @description Invalid range or limit out of bounds. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
        };
    };
    get_backtest_fills: {
        parameters: {
            query: {
                /** @description Inclusive lower bound on `market_ts` (RFC3339). */
                from: string;
                /** @description Exclusive upper bound on `market_ts` (RFC3339). Defaults to `Clock::now()`. */
                to?: string | null;
                /** @description Row cap (defaults to and rejected above `MAX_ORDER_ROWS`). */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Backtest run identifier */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run fills on the window, ordered by ascending `market_ts`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillDto"][];
                };
            };
            /** @description Invalid range or limit out of bounds. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
        };
    };
    get_backtest_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Backtest run identifier */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recomputed PnL/fees metrics for the run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestMetricsDto"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No run with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
        };
    };
    get_backtest_orders: {
        parameters: {
            query: {
                /** @description Inclusive lower bound on `market_ts` (RFC3339). */
                from: string;
                /** @description Exclusive upper bound on `market_ts` (RFC3339). Defaults to `Clock::now()`. */
                to?: string | null;
                /** @description Row cap (defaults to and rejected above `MAX_ORDER_ROWS`). */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Backtest run identifier */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run orders on the window, ordered by ascending `market_ts`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestOrderDto"][];
                };
            };
            /** @description Invalid range or limit out of bounds. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestErrorBody"];
                };
            };
        };
    };
    get_candles: {
        parameters: {
            query: {
                /** @description Exchange identifier as stored in `candles_5s.exchange`. */
                exchange: string;
                /** @description Symbol identifier as stored in `candles_5s.symbol`. */
                symbol: string;
                /** @description Aggregation width (must be one of [`Timeframe::ALLOWED`]). */
                timeframe: string;
                /** @description Inclusive lower bound on `open_time` (RFC3339). */
                from: string;
                /** @description Exclusive upper bound on `open_time` (RFC3339). Defaults to `Clock::now()`. */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated OHLCV buckets ordered by ascending `ts`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleDto"][];
                };
            };
            /** @description Invalid timeframe, range or too many points. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleErrorBody"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected internal error (e.g. schema drift). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleErrorBody"];
                };
            };
        };
    };
    list_strategies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every strategy, ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDto"][];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyErrorBody"];
                };
            };
        };
    };
    get_strategy_fills: {
        parameters: {
            query: {
                /** @description Inclusive lower bound on `executed_at` (RFC3339). */
                from: string;
                /** @description Exclusive upper bound on `executed_at` (RFC3339). Defaults to `Clock::now()`. */
                to?: string | null;
                /** @description Row cap (defaults to [`MAX_ORDER_ROWS`], rejected above it). */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Strategy identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live fills for the strategy on the window, ordered by ascending `executed_at`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveFillDto"][];
                };
            };
            /** @description Invalid range or limit out of bounds. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyErrorBody"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyErrorBody"];
                };
            };
        };
    };
    get_orders: {
        parameters: {
            query: {
                /** @description Inclusive lower bound on `created_at` (RFC3339). */
                from: string;
                /** @description Exclusive upper bound on `created_at` (RFC3339). Defaults to `Clock::now()`. */
                to?: string | null;
                /** @description Row cap (defaults to [`MAX_ORDER_ROWS`], rejected above [`MAX_ORDER_ROWS`]). */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Strategy identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders for the strategy on the requested window, ordered by ascending `created_at`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"][];
                };
            };
            /** @description Invalid range, limit out of bounds, or non-UUID path parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderErrorBody"];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected internal error (e.g. schema drift). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderErrorBody"];
                };
            };
            /** @description Datastore temporarily unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderErrorBody"];
                };
            };
        };
    };
    get_timeframes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allowed aggregation timeframes (finest to coarsest). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Missing or invalid `X-API-Key` header. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
